server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.1.109:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      uri: mongodb://mall-port:123456@192.168.152.131:27017/mall-port


  redis:
    host: 192.168.152.128 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  rabbitmq:
    host: 192.168.152.130
    port: 5672
    virtual-host: /mall
    username: admin
    password: 123456

logging:
  level:
    root: info
    com.dxl.mall: debug

logstash:
  host: localhost

